// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCge2Bp-UPZWxwHwFpSqcDmAGCdA921qpw',
    appId: '1:471490010056:web:62f2ad7435fc03037d3efd',
    messagingSenderId: '471490010056',
    projectId: 'pfeapp-54f2f',
    authDomain: 'pfeapp-54f2f.firebaseapp.com',
    storageBucket: 'pfeapp-54f2f.firebasestorage.app',
    measurementId: 'G-FH5WWYH8JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlX_1rLPWo5Ea0Zl99O4cVjY-gnDNuEBU',
    appId: '1:471490010056:android:d6435e37b27629c57d3efd',
    messagingSenderId: '471490010056',
    projectId: 'pfeapp-54f2f',
    storageBucket: 'pfeapp-54f2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tE0a8HKAHAXiNJnwZe8mnzhc3F3jMwc',
    appId: '1:471490010056:ios:2d2a1b62f3c21b977d3efd',
    messagingSenderId: '471490010056',
    projectId: 'pfeapp-54f2f',
    storageBucket: 'pfeapp-54f2f.firebasestorage.app',
    iosBundleId: 'com.example.mypsyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tE0a8HKAHAXiNJnwZe8mnzhc3F3jMwc',
    appId: '1:471490010056:ios:2d2a1b62f3c21b977d3efd',
    messagingSenderId: '471490010056',
    projectId: 'pfeapp-54f2f',
    storageBucket: 'pfeapp-54f2f.firebasestorage.app',
    iosBundleId: 'com.example.mypsyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCge2Bp-UPZWxwHwFpSqcDmAGCdA921qpw',
    appId: '1:471490010056:web:e2eefd23c4fc2b2b7d3efd',
    messagingSenderId: '471490010056',
    projectId: 'pfeapp-54f2f',
    authDomain: 'pfeapp-54f2f.firebaseapp.com',
    storageBucket: 'pfeapp-54f2f.firebasestorage.app',
    measurementId: 'G-THC74DKNBK',
  );
}
